# ---- Source files ----
ENGINEFILES?=$(wildcard ../src/*.maxj)

MAXPOWER?=$(WHEREISROOT)/lib/maxpower/src
DFESNIPPETS?=$(WHEREISROOT)/lib/dfe-snippets

JFLAGS=-cp $(MAXCOMPILERDIR)/lib/MaxCompiler.jar:$(DFESNIPPETS)/src -1.6 -d .

# XXX A bit of a hack
%.max: $(ENGINEFILES)
	echo $(MXFILEPATH)
	maxjc $(JFLAGS) $(ENGINEFILES)
	MAXAPPJCP=.:$(MAXPOWER) MAXSOURCEDIRS='../src' maxJavaRun -v -m 8192 $(MANAGER) DFEModel=$(DFEModel) enableMPCX=$(MPCX)
